## Business Understanding
Our task for this lab is to create our own logistic regression model which is able to classify how many Uber pickups there will be (low, medium, or high) based off of different information in our dataset. The dataset is a collection of information about Uber pickups like time and location, joined with other data such as the weather for that time and location, what borough it is in, and whether or not it was a NYC public holiday. We split our predictions up by borough because certain boroughs like Manhattan generally always have a higher volume of pickups than boroughs like the Bronx, so aggregate predictions over all of NYC would not have been very insightful. Instead, we make predictions specific to each borough, with the exception of EWR and Staten Island, which we threw out because they did not contain enough data to make accurate predictions. We denote a "high" amount of pickups as greater than half a standard deviation above the mean for that borough. A "low" amount is less than half a standard deviation below the mean for that borough. A "medium" amount is inbetween. 

Our prediction task is valuable because it gives Uber insight into the time periods where they can be most profitable, and time periods where they can save money. For example, on New Years Eve there is most likely an extreme surge in the number of rides requested. If there are not enough drivers to satisfy all of these rides, people will go to Lyft or even just hail a yellow cab. However, if they prepare for this surge by incentivising drivers with an extra percentage of the ride money, there will be more drivers to satisfy the extra rides requests. Our model's insights would help pull in more profits and increases market share compared to treating every day and location as equally profitable. In production, this model would provide the best results if it were deployed so that it would run constantly and react to changing weather conditions, social movements, etc.

In [284]:
import numpy as np

## Data Prep

In [285]:
import pandas as pd
data = pd.read_csv("./data/uber_nyc_enriched.csv")

In [286]:
data.describe()

pickups           spd           vsb          temp          dewp  \
count  29101.000000  29101.000000  29101.000000  29101.000000  29101.000000   
mean     490.215903      5.984924      8.818125     47.669042     30.823065   
std      995.649536      3.699007      2.442897     19.814969     21.283444   
min        0.000000      0.000000      0.000000      2.000000    -16.000000   
25%        1.000000      3.000000      9.100000     32.000000     14.000000   
50%       54.000000      6.000000     10.000000     46.000000     30.000000   
75%      449.000000      8.000000     10.000000     64.500000     50.000000   
max     7883.000000     21.000000     10.000000     89.000000     73.000000   

                slp         pcp01         pcp06         pcp24            sd  
count  29101.000000  29101.000000  29101.000000  29101.000000  29101.000000  
mean    1017.817938      0.003830      0.026129      0.090464      2.529169  
std        7.768796      0.018933      0.093125      0.219402      4.520325  
min      991.400000      0.000000      0.000000      0.000000      0.000000  
25%     1012.500000      0.000000      0.000000      0.000000      0.000000  
50%     1018.200000      0.000000      0.000000      0.000000      0.000000  
75%     1022.900000      0.000000      0.000000      0.050000      2.958333  
max     1043.400000      0.280000      1.240000      2.100000     19.000000

<p> checking for nan or null values in the dataset </p>

In [287]:
data.isnull().values.any()

True

<p> We found only Borough has nan values so we remove the nan rows </p>

In [288]:
data.isnull().any()

pickup_dt    False
borough       True
pickups      False
spd          False
vsb          False
temp         False
dewp         False
slp          False
pcp01        False
pcp06        False
pcp24        False
sd           False
hday         False
dtype: bool

In [289]:
data = data.dropna()

In [290]:
data.isnull().any()

pickup_dt    False
borough      False
pickups      False
spd          False
vsb          False
temp         False
dewp         False
slp          False
pcp01        False
pcp06        False
pcp24        False
sd           False
hday         False
dtype: bool

<p> We found that most of our data didnt have much correlation except temperate and the dew point temperature. We decided to get rid of this variable becasue it seemed very similar to temperature and did not think it would impact the machine learning. </p>

In [291]:
data.corr()

pickups       spd       vsb      temp      dewp       slp     pcp01  \
pickups  1.000000  0.009741 -0.008429  0.063692  0.040082 -0.015708  0.005007   
spd      0.009741  1.000000  0.086177 -0.296126 -0.321606 -0.092761 -0.000357   
vsb     -0.008429  0.086177  1.000000  0.025214 -0.231294  0.167039 -0.488407   
temp     0.063692 -0.296126  0.025214  1.000000  0.896544 -0.224537 -0.013343   
dewp     0.040082 -0.321606 -0.231294  0.896544  1.000000 -0.311156  0.115399   
slp     -0.015708 -0.092761  0.167039 -0.224537 -0.311156  1.000000 -0.089752   
pcp01    0.005007 -0.000357 -0.488407 -0.013343  0.115399 -0.089752  1.000000   
pcp06   -0.002821  0.016668 -0.118346 -0.037295  0.013293 -0.104940  0.128064   
pcp24   -0.022935 -0.010412  0.000895 -0.014408  0.001519 -0.134689  0.000997   
sd      -0.009676  0.097041 -0.047834 -0.545558 -0.489372  0.121508  0.000310   

            pcp06     pcp24        sd  
pickups -0.002821 -0.022935 -0.009676  
spd      0.016668 -0.010412  0.097041  
vsb     -0.118346  0.000895 -0.047834  
temp    -0.037295 -0.014408 -0.545558  
dewp     0.013293  0.001519 -0.489372  
slp     -0.104940 -0.134689  0.121508  
pcp01    0.128064  0.000997  0.000310  
pcp06    1.000000  0.251166  0.039943  
pcp24    0.251166  1.000000  0.069664  
sd       0.039943  0.069664  1.000000

In [292]:
del data['dewp']

<p> We made the holiday column count 1 for yes and 0 for no. </p>

In [293]:
data['hday'] = data['hday'].apply(lambda x: 0 if x=='N' else 1)

<p> We one hot encoded our boroughs becuase they were string values </p>

In [294]:
oneHotCols = pd.get_dummies(data['borough'])
data = data.join(oneHotCols)

In [295]:
del data['borough']

### 1 hot encoding the time of day

<p> We based our hour groups by sunrise and sunset. Night is the time when the sun is down, which on average is from 8pm to 6am. Morning is from 6am till noon. Afternoon is from noon till 5pm. Evening is from 5pm till 8pm, which is around when the sunsets. 

In [296]:
dateTest = data['pickup_dt'][0]
print(int(dateTest[11:13]))
data['is_morning'] = data['pickup_dt'].apply(lambda x: 1 if (int(x[11:13]) >= 6 and int(x[11:13]) < 12) else 0)
data['is_afternoon'] = data['pickup_dt'].apply(lambda x: 1 if (int(x[11:13]) >= 12 and int(x[11:13]) < 17) else 0)
data['is_evening'] = data['pickup_dt'].apply(lambda x: 1 if (int(x[11:13]) >= 17 and int(x[11:13]) < 21) else 0)
data['is_night']  = data['pickup_dt'].apply(lambda x: 1 if (int(x[11:13]) >= 21 or int(x[11:13]) < 6) else 0)

1


### 1 hot encoding the weekday

The weekday from the pickup_dt feature has been 1 hot encoded into monday-sunday. We believe having each day as a feature will help classify & predict the number of ubers necessary at a future date

In [297]:
import datetime
data['is_monday'] = data['pickup_dt'].apply(lambda x: 1 if datetime.date(int(x[0:4]),int(x[5:7]),int(x[8:10])).weekday() == 0 else 0)
data['is_tuesday'] = data['pickup_dt'].apply(lambda x: 1 if datetime.date(int(x[0:4]),int(x[5:7]),int(x[8:10])).weekday() == 1 else 0)
data['is_wednesday'] = data['pickup_dt'].apply(lambda x: 1 if datetime.date(int(x[0:4]),int(x[5:7]),int(x[8:10])).weekday() == 2 else 0)
data['is_thursday'] = data['pickup_dt'].apply(lambda x: 1 if datetime.date(int(x[0:4]),int(x[5:7]),int(x[8:10])).weekday() == 3 else 0)
data['is_friday'] = data['pickup_dt'].apply(lambda x: 1 if datetime.date(int(x[0:4]),int(x[5:7]),int(x[8:10])).weekday() == 4 else 0)
data['is_saturday'] = data['pickup_dt'].apply(lambda x: 1 if datetime.date(int(x[0:4]),int(x[5:7]),int(x[8:10])).weekday() == 5 else 0)
data['is_sunday'] = data['pickup_dt'].apply(lambda x: 1 if datetime.date(int(x[0:4]),int(x[5:7]),int(x[8:10])).weekday() == 6 else 0)

In [298]:
del data['pickup_dt']

<p> We found that the borough EWR averages about 2.4 pickups every 96 hours so we are getting rid of the EWR borough from our dataset. We found that the borough Staten Island averages 1.6 pickups and hour and had a max 13 pickups in an hour over 6 months so we got rid of it from our dataset. </p>

In [299]:
d1 = data.where(data['EWR']==1)[['pickups','EWR']]
print(d1.describe())
d1 = d1.dropna()
data = data[data.EWR == 0]
del data['EWR']
d1 = data.where(data['Staten Island']==1)[['pickups','Staten Island']]
print(d1.describe())
d1 = d1.dropna()
data = data[data['Staten Island'] == 0]
del data['Staten Island']

           pickups     EWR
count  4343.000000  4343.0
mean      0.024177     1.0
std       0.160937     0.0
min       0.000000     1.0
25%       0.000000     1.0
50%       0.000000     1.0
75%       0.000000     1.0
max       2.000000     1.0
           pickups  Staten Island
count  4343.000000         4343.0
mean      1.601888            1.0
std       1.640451            0.0
min       0.000000            1.0
25%       0.000000            1.0
50%       1.000000            1.0
75%       2.000000            1.0
max      13.000000            1.0


## Making our Categories

<p> We have three cateogries of pickup traffic low, medium, high. We found these by finding the mean and standard deviation of each borough. Low is half a standard deviation below the mean and high is half a stadard deviation above the mean. Anything else is counted as a medium amount of pickups. This means that the category of low, medium, and high pickup amount depends on the borough. If we did base our categories by borough then Manhattan would always be in the high pickup amount category and Queens would always be in the low pickup amount category.  </p> 

In [300]:
Man = data[data.Manhattan == 1]
Bronx = data[data.Bronx == 1]
Queens = data[data.Queens == 1]
Brooklyn = data[data.Brooklyn == 1]

print(Man['pickups'].describe())
print(Bronx['pickups'].describe())
print(Queens['pickups'].describe())
print(Brooklyn['pickups'].describe())

count    4343.000000
mean     2387.253281
std      1434.724668
min         0.000000
25%      1223.500000
50%      2269.000000
75%      3293.500000
max      7883.000000
Name: pickups, dtype: float64
count    4343.000000
mean       50.667050
std        31.029223
min         0.000000
25%        29.000000
50%        46.000000
75%        66.000000
max       262.000000
Name: pickups, dtype: float64
count    4343.000000
mean      309.354824
std       154.368300
min         0.000000
25%       196.000000
50%       308.000000
75%       410.000000
max       831.000000
Name: pickups, dtype: float64
count    4343.000000
mean      534.431269
std       294.810182
min         0.000000
25%       331.500000
50%       493.000000
75%       675.000000
max      2009.000000
Name: pickups, dtype: float64


<p> Using the mean and stadard deviation of each borough to place each row of data into a category. We can see that our categories are almost completely balanced within each borough.  </p> 

In [323]:
mstd = Man['pickups'].std()
mmean = Man['pickups'].mean()
bstd = Bronx['pickups'].std()
bmean = Bronx['pickups'].mean()
qstd = Queens['pickups'].std()
qmean = Queens['pickups'].mean()
brstd = Brooklyn['pickups'].std()
brmean = Brooklyn['pickups'].mean()
data['pickupPrediction'] = 0
for index, row in data.iterrows():
    if(row['Manhattan'] == 1):
        if(row['pickups']  < (mmean - mstd/2)):
            data.set_value(index,'pickupPrediction',0)
        elif(row['pickups'] > (mmean + mstd/2)):
            data.set_value(index,'pickupPrediction',2)
        else:
            data.set_value(index,'pickupPrediction',1)
    if(row['Bronx'] == 1):
        if(row['pickups']  < (bmean - bstd/2)):
            data.set_value(index,'pickupPrediction',0)
        elif(row['pickups'] > (bmean + bstd/2)):
            data.set_value(index,'pickupPrediction',2)
        else:
            data.set_value(index,'pickupPrediction',1)
    if(row['Queens'] == 1):
        if(row['pickups']  < (qmean - qstd/2)):
            data.set_value(index,'pickupPrediction',0)
        elif(row['pickups'] > (qmean + qstd/2)):
            data.set_value(index,'pickupPrediction',2)
        else:
            data.set_value(index,'pickupPrediction',1)
    if(row['Brooklyn'] == 1):
        if(row['pickups']  < (brmean - brstd/2)):
            data.set_value(index,'pickupPrediction',0)
        elif(row['pickups'] > (brmean + brstd/2)):
            data.set_value(index,'pickupPrediction',2)
        else:
            data.set_value(index,'pickupPrediction',1)
print(data['pickupPrediction'].describe())
print(data['pickupPrediction'].value_counts())

count    17372.000000
mean         0.935816
std          0.771724
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          2.000000
Name: pickupPrediction, dtype: float64
1    6955
0    5766
2    4651
Name: pickupPrediction, dtype: int64


In [307]:
x = data
y = data['pickupPrediction']
del x['pickupPrediction']

## Metric Used
<p> We believe using an f1-socre would be the best evaluation metric in our case. We need to take into account the false positive and false negative rate because our logisitc regression on the algorithm would always guesses one class which results in a precision of 100% for that class. We care about any form of misclassification of our pickup class prediction. We will give false negatives a higher cost because this means we have too few ubers in an area based off our preditcion. If we have a false positive then it means we have too many ubers in an area, which is bad, but not as bad as having too few. </p>

In [308]:
# from sklearn.preprocessing import StandardScaler
# from sklearn.linear_model import LogisticRegression
# from sklearn.pipeline import Pipeline
# from sklearn.metrics import classification_report

# pipe_lr = Pipeline([('scl', StandardScaler()),
#                     ('clf', LogisticRegression())])

# pipe_lr.fit(xTrain, yTrain)
# y_pred = pipe_lr.predict(xTest)
# print(classification_report(yTest, y_pred))

## Splitting Data
We choose to use continuous test and training sets as our uber pickups were given hourly over a 6 month span. Our algorithm in the real world would be getting the data in hourly and then have to predict based off this new hourly data. We split our data into 10 folds splitting our data by the time that it occured. 

In [309]:
x.reset_index(inplace=True, drop=True)
y.reset_index(inplace=True, drop=True)

pd.set_option('display.max_columns', 500)
x.describe()

pickups           spd           vsb          temp           slp  \
count  17372.000000  17372.000000  17372.000000  17372.000000  17372.000000   
mean     820.426606      6.000039      8.820027     47.489005   1017.812802   
std     1179.027565      3.706364      2.443018     19.772345      7.783546   
min        0.000000      0.000000      0.000000      2.000000    991.400000   
25%       86.000000      3.000000      9.100000     31.500000   1012.400000   
50%      367.000000      6.000000     10.000000     45.000000   1018.200000   
75%      789.250000      8.000000     10.000000     64.000000   1023.000000   
max     7883.000000     21.000000     10.000000     89.000000   1043.400000   

              pcp01         pcp06         pcp24            sd          hday  \
count  17372.000000  17372.000000  17372.000000  17372.000000  17372.000000   
mean       0.003821      0.026074      0.091036      2.536496      0.038453   
std        0.018834      0.092917      0.220437      4.520593      0.192292   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.051667      3.166667      0.000000   
max        0.280000      1.240000      2.100000     19.000000      1.000000   

              Bronx      Brooklyn     Manhattan        Queens    is_morning  \
count  17372.000000  17372.000000  17372.000000  17372.000000  17372.000000   
mean       0.250000      0.250000      0.250000      0.250000      0.250058   
std        0.433025      0.433025      0.433025      0.433025      0.433058   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.250000      0.250000      0.250000      0.250000      1.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

       is_afternoon    is_evening      is_night     is_monday    is_tuesday  \
count  17372.000000  17372.000000  17372.000000  17372.000000  17372.000000   
mean       0.208381      0.166705      0.374856      0.143679      0.143679   
std        0.406163      0.372723      0.484100      0.350775      0.350775   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      1.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

       is_wednesday   is_thursday     is_friday   is_saturday     is_sunday  
count  17372.000000  17372.000000  17372.000000  17372.000000  17372.000000  
mean       0.138153      0.143449      0.143679      0.143679      0.143679  
std        0.345071      0.350540      0.350775      0.350775      0.350775  
min        0.000000      0.000000      0.000000      0.000000      0.000000  
25%        0.000000      0.000000      0.000000      0.000000      0.000000  
50%        0.000000      0.000000      0.000000      0.000000      0.000000  
75%        0.000000      0.000000      0.000000      0.000000      0.000000  
max        1.000000      1.000000      1.000000      1.000000      1.000000

<p> The data was already in order by hour. Each four rows represented one boroughs uber and weather data. We split our data into 10 folds for training. </p>

In [310]:
from sklearn.model_selection import TimeSeriesSplit
tscv = TimeSeriesSplit(n_splits=10)
for train_index, test_index in tscv.split(x.values,y.values):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x.iloc[train_index], x.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

TRAIN: [   0    1    2 ... 1579 1580 1581] TEST: [1582 1583 1584 ... 3158 3159 3160]
TRAIN: [   0    1    2 ... 3158 3159 3160] TEST: [3161 3162 3163 ... 4737 4738 4739]
TRAIN: [   0    1    2 ... 4737 4738 4739] TEST: [4740 4741 4742 ... 6316 6317 6318]
TRAIN: [   0    1    2 ... 6316 6317 6318] TEST: [6319 6320 6321 ... 7895 7896 7897]
TRAIN: [   0    1    2 ... 7895 7896 7897] TEST: [7898 7899 7900 ... 9474 9475 9476]
TRAIN: [   0    1    2 ... 9474 9475 9476] TEST: [ 9477  9478  9479 ... 11053 11054 11055]
TRAIN: [    0     1     2 ... 11053 11054 11055] TEST: [11056 11057 11058 ... 12632 12633 12634]
TRAIN: [    0     1     2 ... 12632 12633 12634] TEST: [12635 12636 12637 ... 14211 14212 14213]
TRAIN: [    0     1     2 ... 14211 14212 14213] TEST: [14214 14215 14216 ... 15790 15791 15792]
TRAIN: [    0     1     2 ... 15790 15791 15792] TEST: [15793 15794 15795 ... 17369 17370 17371]


In [311]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 1/5, random_state = 0)

## Modeling

In [319]:
# how do we compare now to sklearn?
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression as LogisticRegressionSci
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
import matplotlib.pyplot as plt
#From Sklearn documentation 
def plot_confusion_matrix(y_true, y_pred, classes,
                          normalize=False,
                          title=None,
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if not title:
        if normalize:
            title = 'Normalized confusion matrix'
        else:
            title = 'Confusion matrix, without normalization'

    # Compute confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    # Only use the labels that appear in the data
    classes = list(unique_labels(y_true, y_pred))
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    fig, ax = plt.subplots()
    im = ax.imshow(cm, interpolation='nearest', cmap=cmap)
    ax.figure.colorbar(im, ax=ax)
    # We want to show all ticks...
    ax.set(xticks=np.arange(cm.shape[1]),
           yticks=np.arange(cm.shape[0]),
           # ... and label them with the respective list entries
           xticklabels=classes, yticklabels=classes,
           title=title,
           ylabel='True label',
           xlabel='Predicted label')

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
             rotation_mode="anchor")

    # Loop over data dimensions and create text annotations.
    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, format(cm[i, j], fmt),
                    ha="center", va="center",
                    color="white" if cm[i, j] > thresh else "black")
    fig.tight_layout()
    return ax

In [430]:
# Example adapted from https://github.com/rasbt/python-machine-learning-book/blob/master/code/ch12/ch12.ipynb
# Original Author: Sebastian Raschka

# This is the optional book we use in the course, excellent intuitions and straightforward programming examples
# please note, however, that this code has been manipulated to reflect our assumptions and notation.
import numpy as np
from scipy.special import expit
import sys
import pandas as pd

# start with a simple base classifier, which can't be fit or predicted
# it only has internal classes to be used by classes that will subclass it
class TwoLayerPerceptronBase(object):
    def __init__(self, n_hidden=30,
                 C=0.0, epochs=500, eta=0.001, random_state=None,
                act_func='sigmoid',cost_func='quadratic',layers=2):
        np.random.seed(random_state)
        self.n_hidden = n_hidden
        self.l2_C = C
        self.epochs = epochs
        self.eta = eta
        self.act_func = act_func
        self.cost_func = cost_func
        self.layers = layers
        
    @staticmethod
    def _encode_labels(y):
        """Encode labels into one-hot representation"""
        onehot = pd.get_dummies(y).values.T
            
        return onehot

    def _initialize_weights(self):
        W = []
        """Initialize weights with small random numbers."""
        W1_num_elems = (self.n_features_ + 1)*self.n_hidden
        W1 = np.random.uniform(-1.0, 1.0, size=W1_num_elems)
        W1 = W1.reshape(self.n_hidden, self.n_features_ + 1) # reshape to be W
        W.append(W1)
        for i in range(0,self.layers-2):
            W1_num_elems = (self.n_hidden + 1)*self.n_hidden
            W1 = np.random.uniform(-1.0, 1.0, size=W1_num_elems)
            W1 = W1.reshape(self.n_hidden, self.n_hidden + 1) # reshape to be W
            W.append(W1)
        W2_num_elems = (self.n_hidden + 1)*self.n_output_
        W2 = np.random.uniform(-1.0, 1.0, size=W2_num_elems)
        W2 = W2.reshape(self.n_output_, self.n_hidden + 1)
        W.append(W2)
        return W
    
    @staticmethod
    def _sigmoid(z):
        """Use scipy.special.expit to avoid overflow"""
        # 1.0 / (1.0 + np.exp(-z))
        return expit(z)
    
    
    @staticmethod
    def _add_bias_unit(X, how='column'):
        """Add bias unit (column or row of 1s) to array at index 0"""
        if how == 'column':
            ones = np.ones((X.shape[0], 1))
            X_new = np.hstack((ones, X))
        elif how == 'row':
            ones = np.ones((1, X.shape[1]))
            X_new = np.vstack((ones, X))
        return X_new
    
    @staticmethod
    def _L2_reg(lambda_, W1, W2):
        """Compute L2-regularization cost"""
        # only compute for non-bias terms
        return (lambda_/2.0) * np.sqrt(np.mean(W1[:, 1:] ** 2) + np.mean(W2[:, 1:] ** 2))
    
    def _cost(self,A3,Y_enc,W1,W2):
        '''Get the objective function value'''
        if(self.cost_func == 'quadratic'):
            cost = np.mean((Y_enc-A3)**2)
        else:
            cost = -np.mean(np.nan_to_num((Y_enc*np.log(A3)+(1-Y_enc)*np.log(1-A3))))
        L2_term = self._L2_reg(self.l2_C, W1, W2)
        return cost + L2_term

In [483]:
class TwoLayerPerceptron(TwoLayerPerceptronBase):
    def _feedforward(self, X, W1, W2):
        """Compute feedforward step
        -----------
        X : Input layer with original features.
        W1: Weight matrix for input layer -> hidden layer.
        W2: Weight matrix for hidden layer -> output layer.
        ----------
        a1-a3 : activations into layer (or output layer)
        z1-z2 : layer inputs 

        """
        A1 = self._add_bias_unit(X.T, how='row')
        Z1 = W1 @ A1
        if(self.act_func == 'sigmoid'):
            A2 = self._sigmoid(Z1)
        else:
            A2 = Z1
        A2 = self._add_bias_unit(A2, how='row')
        Z2 = W2 @ A2
        A3 = self._sigmoid(Z2)
        return A1, Z1, A2, Z2, A3
    
    def _get_gradient(self, A1, A2, A3, Z1, Z2, Y_enc, W1, W2):
        """ Compute gradient step using backpropagation.
        """
        # backpropagation
        grad1 = np.zeros(W1.shape)
        grad2 = np.zeros(W2.shape)
        ones = np.ones(self.n_hidden + 1)
        # for each instance's activations 
        for (a1,a2,a3,y) in zip(A1.T,A2.T,A3.T,Y_enc.T):
#             print('a3',a3.shape)
#             print('y',y.shape)
            if(self.cost_func == 'quadratic'):
                dJ_dz2 = -2*(y - a3)*a3*(1-a3)
            else:
                dJ_dz2 = a3-y
            #loop here? but then a2 never changes 
            if(self.act_func == 'sigmoid'):
                dJ_dz1 = dJ_dz2 @ W2 @ np.diag(a2*(1-a2))
            else:
                dJ_dz1 = dJ_dz2 @ W2 @ np.diag(ones)
                # print(dJ_dz1.shape)
            grad2 += dJ_dz2[:,np.newaxis]  @ a2[np.newaxis,:]
            grad1 += dJ_dz1[1:,np.newaxis] @ a1[np.newaxis,:] 
            # don't incorporate bias term in the z1 gradient 
            # (its added in a2 from another layer)
            

        # regularize weights that are not bias terms
        grad1[:, 1:] += (W1[:, 1:] * self.l2_C)
        grad2[:, 1:] += (W2[:, 1:] * self.l2_C)

        return grad1, grad2
    
    def predict(self, X):
        """Predict class labels"""
        for i in range(0,len(self.W)-1):
            if(i>0):
                X = A3.T
            _, _, _, _, A3 = self._feedforward(X,self.W[i], self.W[i+1])
        y_pred = np.argmax(A3, axis=0)
        return y_pred
    
    
    def fit(self, X, y, print_progress=False):
        """ Learn weights from training data."""
        
        X_data, y_data = X.copy(), y.copy()
        Y_enc = self._encode_labels(y)
        
        # init weights and setup matrices
        self.n_features_ = X_data.shape[1]
        self.n_output_ = Y_enc.shape[0]
        self.W = self._initialize_weights()

        self.cost_ = []
        for i in range(self.epochs):

            if print_progress>0 and (i+1)%print_progress==0:
                sys.stderr.write('\rEpoch: %d/%d' % (i+1, self.epochs))
                sys.stderr.flush()
            # feedforward all instances
            W1 = []
            W2 = []
            A1arr = []
            A2arr = []
            A3arr = []
            Z1arr = []
            Z2arr = []
            X_data = X.copy()
            for i2 in range(0,len(self.W)-1):
                W1 = self.W[i2]
                W2 = self.W[i2+1]
                if(i2>0):
                    X_data = A3.T
                A1, Z1, A2, Z2, A3 = self._feedforward(X_data,W1,W2)
                A1arr.append(A1)
                A2arr.append(A2)
                A3arr.append(A3)
                Z1arr.append(Z1)
                Z2arr.append(Z2)
            cost = self._cost(A3,Y_enc,W1,W2)
            self.cost_.append(cost)
            for i2 in range(len(self.W)-1,0,-1):
                # compute gradient via backpropagation
                print(i2)
                if(i2 < len(self.W)-1):
                    Y_enc = A3arr[i2-1]
                print(Y_enc)
                ## return an array of gradients to update weight array
                ## iterate inside of get gradient function instead
                grad1, grad2 = self._get_gradient(A1=A1arr[i2-1], A2=A2arr[i2-1], A3=A3arr[i2-1], Z1=Z1arr[i2-1],
                                                  Z2=Z2arr[i2-1]
                                                  ,Y_enc=Y_enc, W1=self.W[i2-1], W2=self.W[i2])
                self.W[i2-1] -= self.eta * grad1
                self.W[i2] -= self.eta * grad2
            

        return self

In [484]:
params = dict(n_hidden=50, 
                C=0.1,
                epochs=50,
                eta=0.001,
                random_state=1,
                act_func='sigmoid',
                cost_func='reag',
                layers=3)

In [485]:
%%time 
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
nn = TwoLayerPerceptron(**params)
i = 1
for train_index, test_index in tscv.split(x.values,y.values):
    print('fold', i)
    X_train, X_test = x.iloc[train_index], x.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    nn.fit(X_train, y_train, print_progress=10)
    yhat = nn.predict(X_test)
    class_names = ['low','medium','high']
    plot_confusion_matrix(y_test, yhat, classes=class_names,
                      title='SciKit Learn Implementation')
    print('Test acc:',f1_score(y_test,yhat,average=None))
    i +=1

fold 1
2
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 1]
 [1 1 1 ... 0 0 0]]
1
[[0.19226049 0.33873069 0.64819516 ... 0.19226049 0.36782159 0.74366688]
 [0.09635857 0.58109012 0.72602907 ... 0.09635857 0.19523399 0.04389513]
 [0.26181301 0.48856364 0.22499308 ... 0.26181301 0.4736671  0.26038765]
 ...
 [0.67463544 0.73598046 0.87826558 ... 0.67463544 0.58375395 0.45636033]
 [0.98182177 0.97609647 0.99862538 ... 0.98182177 0.96841328 0.97794939]
 [0.99895704 0.97857473 0.99526761 ... 0.99895704 0.99948101 0.99695669]]


ValueError: operands could not be broadcast together with shapes (50,1582) (3,1582) 